export const CHANNEL_DEFINITIONS = [
    { channel_id: "feishu", label: "飞书" },
    { channel_id: "wechat-work", label: "企业微信" },
    { channel_id: "dingtalk", label: "钉钉" },
    { channel_id: "wechat", label: "微信" },
    { channel_id: "qq-bot", label: "QQ Bot" }
];
export const ERROR_CODES = {
    SERVICE_NOT_RUNNING: "SERVICE_NOT_RUNNING",
    SERVICE_START_FAILED: "SERVICE_START_FAILED",
    SERVICE_STOP_FAILED: "SERVICE_STOP_FAILED",
    SERVICE_RESTART_FAILED: "SERVICE_RESTART_FAILED",
    MODEL_PROVIDER_IN_USE: "MODEL_PROVIDER_IN_USE",
    MODEL_AUTH_FAILED: "MODEL_AUTH_FAILED",
    MODEL_PROBE_FAILED: "MODEL_PROBE_FAILED",
    CHANNEL_NOT_FOUND: "CHANNEL_NOT_FOUND",
    CHANNEL_CONFIG_INVALID: "CHANNEL_CONFIG_INVALID",
    CHANNEL_PROBE_FAILED: "CHANNEL_PROBE_FAILED",
    CONFIG_PATCH_FAILED: "CONFIG_PATCH_FAILED",
    CONFIG_APPLY_FAILED: "CONFIG_APPLY_FAILED",
    LOG_TAIL_FAILED: "LOG_TAIL_FAILED",
    LOG_STREAM_FAILED: "LOG_STREAM_FAILED"
};
